lineage-display-config:
  rules:
    incomplete:
      - edgeType: Classification
        destinationNodeType: Incomplete
    invertEdge:
      - edgeType: SemanticAssignment
        destinationNodeType: GlossaryTerm
        sourceNodeType: GlossaryCategory
      - edgeType: TermCategorization
        destinationNodeType: GlossaryTerm
        sourceNodeType: GlossaryCategory
    primaryCategory:
      - edgeType: Classification
        sourceNodeType: GlossaryTerm
        destinationNodeType: PrimaryCategory
        classificationProperty: categoryQualifiedName
    removeNodes:
      - queriedNodeType: TabularFileColumn
        nodeTypesToRemove:
          - TabularSchemaType

