# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.
---
name: "Check documentation links"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    if: startsWith(github.repository,'odpi/')
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.4.1
        with:
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
