# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.
name: "Release (Java8, Maven)"

# Trigger when a Release is created in github 
# - does not run on modification (may be just text)

on:
  # No checks for branch or repo - assuming release creation is manual, controlled
  release:
    types:
      - created
  # Also allow for manual invocation for testing
  workflow_dispatch:
  


jobs:
  build:
    runs-on: ubuntu-latest
    name: "Release"
    steps:
      - uses: actions/checkout@v2
        name: Checkout source
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          # Java 1.8 is used for final released build
          java-version: 1.8
          # Publishing attributes for maven central (this step adds to setting.xml)
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          # Keys must be known to maven central - require broad publishing
          gpg-private-key: ${{ secrets.OSSRH_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      # Normal build (in future may also run reports (site))
      - name: Build with Maven
        run: mvn -B -DuseMavenCentral clean verify
        # Needed for publishing -- note we push to a staging area, login to oss.sonatype.org to 
        # verify (close) the repository & release
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_PASSPHRASE }}
      # Mostly for verification - not published to the release itself for now
      - name: Upload assemblies
        uses: actions/upload-artifact@v2
        with:
          name: Assemblies
          path: open-metadata-distribution/open-metadata-assemblies/target/*.gz
